SCREEN_WIDTH = 1800 
SCREEN_HEIGHT = 800 

# Scroll settings
SCROLL_SPEED_RATIO = 0.01
SCROLL_SPEED = int(SCROLL_SPEED_RATIO * SCREEN_WIDTH)

# Initialize aircraft
INITIAL_AIRCRAFT_WIDTH = 0.1 * SCREEN_WIDTH
INITIAL_AIRCRAFT_HEIGHT = 0.05 * SCREEN_HEIGHT
INITIAL_AIRCRAFT_X = 0.1 * SCREEN_WIDTH
INITIAL_AIRCRAFT_Y = 0.5 * SCREEN_HEIGHT

# Initialize bullet
INITIAL_BULLET_X = 0.1 * SCREEN_WIDTH
INITIAL_BULLET_Y = 0.1 * SCREEN_HEIGHT
SHOOT_COOLDOWN = 400

INITIAL_ENEMY_AIRCRAFT = 1
ENEMY_COUNT_INCREMENT = 0.5

INITIAL_LIVES = 10

# Spawn enemy aircraft in waves instead of persistently.
WAVE_MODE = False
