SCREEN_WIDTH = 1800 
SCREEN_HEIGHT = 800
ASSET_FOLDER = "./assets"
SHOW_FPS = False

# Scroll settings
SCROLL_SPEED_RATIO = 0.01
SCROLL_SPEED = int(SCROLL_SPEED_RATIO * SCREEN_WIDTH)

# Initialize aircraft
INITIAL_AIRCRAFT_WIDTH = 0.1 * SCREEN_WIDTH
INITIAL_AIRCRAFT_HEIGHT = 0.05 * SCREEN_HEIGHT
INITIAL_AIRCRAFT_X = 0.1 * SCREEN_WIDTH
INITIAL_AIRCRAFT_Y = 0.5 * SCREEN_HEIGHT

# Weapons
BULLET_VELOCITY = 20
WEAPON_RELATIVE_VELOCITY_MULTIPLIER = 0.2
BOMB_X_VELOCITY_DECAY = 0.05
BOMB_Y_VELOCITY_GAIN = 0.1
BOMB_TERMINAL_VELOCITY = 20
SHOOT_COOLDOWN = 400
PLAYER_SHOOT_COOLDOWN = 400
SPAWN_COOLDOWN = 1000
BOMB_COOLDOWN = 1000
PLAYER_BOMB_COOLDOWN = 1000

INITIAL_ENEMY_AIRCRAFT = 1
ENEMY_COUNT_INCREMENT = 0.4

INITIAL_HEALTH = 100

# Spawn enemy aircraft in waves instead of persistently.
WAVE_MODE = True

# Enemy Settings
INITIAL_ENEMY_SPEED = 1

# Easter eggs
MOTH_CHANCE = 0.001
MOTH_MUSIC = True
BERRY_BOMB_CHANCE = 0.001
