import pygame as pg

QUIT = pg.K_ESCAPE

SHOOT = pg.MOUSEBUTTONDOWN
SHOOT_2 = pg.K_x

RAPID_FIRE = pg.K_LSHIFT
BOMB = pg.K_SPACE

DEBUG_SPAWN_ENEMY = pg.K_l
DEBUG_SPAWN_MOTH = pg.K_c
DEBUG_SPAWN_PARTICLE = pg.K_p
DEBUG_KILL_ALL = pg.K_m
DEBUG_RAPID_FIRE = pg.K_n

PITCH_UP = pg.K_w
PITCH_DOWN = pg.K_s
